# Generated by Django 3.2 on 2021-09-22 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuotas',
            fields=[
                ('id_cuota', models.IntegerField(primary_key=True, serialize=False)),
                ('personapago', models.CharField(max_length=60)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecharealizacion', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('numero_socio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='numsociocuotas', to='Socios.socios')),
            ],
            options={
                'verbose_name': 'cuota',
                'verbose_name_plural': 'cuotas',
                'db_table': 'cuotas',
                'ordering': ['id_cuota'],
            },
        ),
    ]
