# Generated by Django 3.2 on 2021-09-22 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmacias', '0001_initial'),
        ('Profesionales', '0001_initial'),
        ('Socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicamentos',
            fields=[
                ('id_medicamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('presentacion', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('cod_farmacia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Farmacias.farmacias')),
            ],
            options={
                'verbose_name': 'medicamento',
                'verbose_name_plural': 'medicamentos',
                'db_table': 'medicamentos',
                'ordering': ['id_medicamento'],
            },
        ),
        migrations.CreateModel(
            name='receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('paciente', models.CharField(max_length=60)),
                ('diagnostico', models.TextField(max_length=200)),
                ('fecha', models.DateField()),
                ('carencia', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('cod_farmacia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Farmacias.farmacias')),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Medicamentos.medicamentos')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Profesionales.profesionales')),
                ('numero_socio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Socios.socios')),
            ],
            options={
                'verbose_name': 'receta',
                'verbose_name_plural': 'recetas',
                'db_table': 'recetas',
                'ordering': ['numero_socio'],
            },
        ),
    ]
