deptos_tucuman = [
    ("Burruyacú", "1- Burruyacú"),
    ("Capital", "2- Capital"),
    ("Chicligasta", "3- Chicligasta"),
    ("Cruz Alta", "4- Cruz Alta"),
    ("Famaillá", "5- Famaillá"),
    ("Graneros", "6- Graneros"),
    ("Juan Bautista Alberdi", "7- Juan Bautista Alberdi"),
    ("La Cocha", "8- La Cocha"),
    ("Leales", "9- Leales"),
    ("Lules", "10- Lules"),
    ("Monteros", "11- Monteros"),
    ("Río Chico", "12- Río Chico"),
    ("Simoca", "13- Simoca"),
    ("Tafí del Valle", "14- Tafí del Valle"),
    ("Tafí Viejo", "15- Tafí Viejo"),
    ("Trancas", "16- Trancas"),
    ("Yerba Buena", "17- Yerba Buena"),
]

provincias = [
    ("Buenos Aires", "1- Buenos Aires"),
    ("Catamarca", "2- Catamarca"),
    ("Chaco", "3- Chaco"),
    ("Chubut", "4- Chubut"),
    ("Córdoba", "5- Córdoba"),
    ("Corrientes", "6- Corrientes"),
    ("Entre Ríos", "7- Entre Ríos"),
    ("Formosa", "8- Formosa"),
    ("Jujuy", "9- Jujuy"),
    ("La Pampa", "10- La Pampa"),
    ("La Rioja", "11- La Rioja"),
    ("Mendoza", "12- Mendoza"),
    ("Misiones", "13- Misiones"),
    ("Neuquén", "14- Neuquén"),
    ("Río Negro", "15- Río Negro"),
    ("Salta", "16- Salta"),
    ("San Juan", "17- San Juan"),
    ("San Luis", "18- San Luis"),
    ("Santa Cruz", "19- Santa Cruz"),
    ("Santa Fe", "20- Santa Fe"),
    ("Santiago del Estero", "21- Santiago del Estero"),
    ("Tierra del Fuego", "22- Tierra del Fuego"),
    ("Tucumán", "23- Tucumán"),
]
