# Generated by Django 3.2 on 2021-09-22 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='socios',
            fields=[
                ('numero_socio', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=80)),
                ('dni', models.IntegerField(unique=True)),
                ('calle', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=30)),
                ('departamento', models.CharField(choices=[('Burruyacú', '1- Burruyacú'), ('Capital', '2- Capital'), ('Chicligasta', '3- Chicligasta'), ('Cruz Alta', '4- Cruz Alta'), ('Famaillá', '5- Famaillá'), ('Graneros', '6- Graneros'), ('Juan Bautista Alberdi', '7- Juan Bautista Alberdi'), ('La Cocha', '8- La Cocha'), ('Leales', '9- Leales'), ('Lules', '10- Lules'), ('Monteros', '11- Monteros'), ('Río Chico', '12- Río Chico'), ('Simoca', '13- Simoca'), ('Tafí del Valle', '14- Tafí del Valle'), ('Tafí Viejo', '15- Tafí Viejo'), ('Trancas', '16- Trancas'), ('Yerba Buena', '17- Yerba Buena')], max_length=30)),
                ('cod_postal', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField(blank=True, editable=False, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('tel_fijo', models.IntegerField(blank=True, null=True)),
                ('tel_celular', models.IntegerField(blank=True, null=True)),
                ('carencia', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'socio',
                'verbose_name_plural': 'socios',
                'db_table': 'socios',
                'ordering': ['numero_socio'],
            },
        ),
        migrations.CreateModel(
            name='familiar',
            fields=[
                ('dni_familiar', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('carencia', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('numero_socio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Socios.socios')),
            ],
            options={
                'verbose_name': 'familiar',
                'verbose_name_plural': 'familiares',
                'db_table': 'familiares',
                'ordering': ['numero_socio'],
            },
        ),
    ]
