# Generated by Django 3.2 on 2021-09-22 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mutuales',
            fields=[
                ('id_mutual', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sucursal', models.CharField(choices=[('Burruyacú', '1- Burruyacú'), ('Capital', '2- Capital'), ('Chicligasta', '3- Chicligasta'), ('Cruz Alta', '4- Cruz Alta'), ('Famaillá', '5- Famaillá'), ('Graneros', '6- Graneros'), ('Juan Bautista Alberdi', '7- Juan Bautista Alberdi'), ('La Cocha', '8- La Cocha'), ('Leales', '9- Leales'), ('Lules', '10- Lules'), ('Monteros', '11- Monteros'), ('Río Chico', '12- Río Chico'), ('Simoca', '13- Simoca'), ('Tafí del Valle', '14- Tafí del Valle'), ('Tafí Viejo', '15- Tafí Viejo'), ('Trancas', '16- Trancas'), ('Yerba Buena', '17- Yerba Buena')], max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mutual',
                'verbose_name_plural': 'mutuales',
                'db_table': 'mutuales',
                'ordering': ['id_mutual'],
            },
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'servicios',
                'ordering': ['servicio'],
            },
        ),
        migrations.CreateModel(
            name='servicio_mutual',
            fields=[
                ('id_serv_mut', models.AutoField(primary_key=True, serialize=False)),
                ('id_mutual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mutuales.mutuales')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mutuales.servicios')),
            ],
            options={
                'verbose_name': 'servicio_mutual',
                'verbose_name_plural': 'servicios_mutual',
                'db_table': 'servicio_mutuales',
                'ordering': ['id_mutual'],
                'unique_together': {('id_mutual', 'id_servicio')},
            },
        ),
    ]
