# Generated by Django 3.2 on 2021-09-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farmacias',
            fields=[
                ('cod_farmacia', models.IntegerField(primary_key=True, serialize=False)),
                ('matricula_farm', models.IntegerField(unique=True)),
                ('farmacia', models.CharField(max_length=50)),
                ('cuit', models.IntegerField(unique=True)),
                ('direccion', models.CharField(max_length=80)),
                ('localidad', models.CharField(max_length=30)),
                ('provincia', models.CharField(choices=[('Buenos Aires', '1- Buenos Aires'), ('Catamarca', '2- Catamarca'), ('Chaco', '3- Chaco'), ('Chubut', '4- Chubut'), ('Córdoba', '5- Córdoba'), ('Corrientes', '6- Corrientes'), ('Entre Ríos', '7- Entre Ríos'), ('Formosa', '8- Formosa'), ('Jujuy', '9- Jujuy'), ('La Pampa', '10- La Pampa'), ('La Rioja', '11- La Rioja'), ('Mendoza', '12- Mendoza'), ('Misiones', '13- Misiones'), ('Neuquén', '14- Neuquén'), ('Río Negro', '15- Río Negro'), ('Salta', '16- Salta'), ('San Juan', '17- San Juan'), ('San Luis', '18- San Luis'), ('Santa Cruz', '19- Santa Cruz'), ('Santa Fe', '20- Santa Fe'), ('Santiago del Estero', '21- Santiago del Estero'), ('Tierra del Fuego', '22- Tierra del Fuego'), ('Tucumán', '23- Tucumán')], max_length=30)),
                ('cod_postal', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('tel_fijo', models.IntegerField(blank=True, null=True)),
                ('representante', models.CharField(max_length=50)),
                ('tel_celular', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'famacia',
                'verbose_name_plural': 'farmacias',
                'db_table': 'farmacias',
                'ordering': ['cod_farmacia'],
            },
        ),
    ]
