# Generated by Django 3.2 on 2021-09-22 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profesionales', '0001_initial'),
        ('Mutuales', '0001_initial'),
        ('Socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordenes',
            fields=[
                ('numero_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('paciente', models.CharField(max_length=60)),
                ('servicio', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('realizado', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Profesionales.profesionales')),
                ('id_mutual', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mutuales.mutuales')),
                ('numero_socio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Socios.socios')),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
                'db_table': 'ordenes',
                'ordering': ['numero_orden'],
            },
        ),
    ]
